# Schema for the configuration files of the SPH Config module.

# Slick global settings managed by UI.
sph_config.sphconfig:
  type: config_object
  label: 'SPH Config'
  mapping:
    enable:
      type: boolean
      label: 'Enable Enable 3rd Party API'
    api_key:
      type: string
      label: 'API Key'
    summary:
      type: string
      label: 'Summary'
